apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-tool-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ip-tool
  template:
    metadata:
      labels:
        app: ip-tool
    spec:
      containers:
      - name: ip-tool
        image: gcr.io/gcpopenshift/ip-tool
        command: ["python3", "ip-tool.py"]